listeners:
- motd: ${CFG_MOTD}
  priorities:
  - main
  host: 0.0.0.0:25565
  max_players: 20
  force_default_server: false
  tab_size: 60
  tab_list: GLOBAL_PING
  bind_local_address: true
  ping_passthrough: false
  query_enabled: false
  query_port: 25577
  proxy_protocol: false
remote_ping_cache: -1
network_compression_threshold: 256
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: false
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
online_mode: true
forge_support: false
servers:
  main:
    address: mc-main:25565
    restricted: false
    motd: ${CFG_MOTD}
  creative:
    address: mc-creative:25565
    restricted: false
    motd: ${CFG_MOTD}
  lan-games:
    address: mc-lan-games:25565
    restricted: false
    motd: ${CFG_MOTD}
